swagger: "2.0"
info:
  title: CSV Importer
  version: __VERSION__
  contact:
    name: Abhishek Goswami
    email: abhishekg785@gmail.com

paths:
  /healthcheck:
    get:
      summary: API Healthcheck
      responses:
        204:
          description: API is healthy
        default:
          description: API is not healthy
  /search:
    post:
      summary: Search for the data in the csv
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
                required: true
      responses:
        201:
          description: Result
  /autocomplete:
    get:
      summary: Gets the suggestions on the basis of the given query param
      parameters:
        - in : query
          name: query
          schema:
            type: integer
          description: The value to search for in the data
        - in : query
          name: field
          schema:
            type: string
          description: The field value to search for in the data such as name, age etc
        - in : query
          name: limit
          schema:
            type: integer
          description: The number of values to fetch
      responses:
        201:
          description: Result