swagger: "2.0"
info:
  title: CSV Importer
  version: __VERSION__
  contact:
    name: Abhishek Goswami
    email: abhishekg785@gmail.com

paths:
  /healthcheck:
    get:
      summary: API Healthcheck
      responses:
        204:
          description: API is healthy
        default:
          description: API is not healthy
  /search:
    post:
      summary: Search for the data in the csv
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
                required: true
      responses:
        201:
          description: Result